### ISSUE TITLE
Installing a selected package

### ISSUE THREAD

**Issue by Biomicrogen** [marbl/metAMOS#177]
How can I install only a single package using the INSTALL.py route, or can I not?  I have already installed core, imetamos, optional, and deprecated.   I tried 
sudo python INSTALL.py Mira amd it reinstalled everything.  Can I install packages piecemeal?

**Comment by Biomicrogen** [comment]
I just noticed that mira is included in the packages I have already installed....is it not included in the imetamos pipeline?  Also, how can I enable the functional annotation portion of the iMetamos pipeline?

**Comment by Biomicrogen** [comment]
Also, I get this error:
Error: cannot find MPI, required to build Ray. Please add it to your path.
 I've looked everywhere for a reference to MPI, I do not know what it is?

**Comment by skoren** [comment]
1. MPI stands for Message Passing Interface (http://en.wikipedia.org/wiki/Message_Passing_Interface). It is an API to allow multiple computers to communicate and run parallel tasks. Several assemblers (Ray and ABySS, most notably) use MPI for their parallel infrastructure. Since MPI must be configured on all the systems in your environment, it cannot be installed/managed by metAMOS and so needs to be configured beforehand. If you do not have it, you won't be able to compile Ray and will only be able to use ABySS in single-threaded mode.

2. You can definitely install individual packages. When you run INSTALL.py mira it will still list all the tools that have to be installed (as it recognizes that you've already installed core/imetamos/etc) but will only download/compile those tools that are missing. I've verified this is the behavior on our system. If any of the tools failed to be installed on the first run, INSTALL.py will attempt to install them again. Mira will be installed as part of the iMetAMOS pipeline and you can run it by adding mira to the -a option for runPipeline. Did you get error messages from your INSTALL.py run? If you did, could you post all the output produced by INSTALL.py?

3. FunctionalAnnotation is skipped by default unless a user requests it to speed up the pipeline. To enable functional annotation, add -f FunctionalAnnotation to your runPipeline commmand.
