### ISSUE TITLE
Unable to run pipeline

### ISSUE THREAD

**Issue by shaman-narayanasamy** [marbl/metAMOS#178]
Dear authors, 

I installed metAMOS_v1.5rc2_binary on a cluster which runs Debian Linux operating system, version 6 (Squeeze) following these instructions:
http://metamos.readthedocs.org/en/v1.5rc3/content/frozenbinary.html

I attempted to run the pipeline on the test data.

```
Project dir /mnt/src_nfs1/projects/ecosystem_biology/local_tools/metAMOS_v1.5rc2_binary/Test/test_fast successfully created!
Use runPipeline.py to start Pipeline
Warning: Cannot determine OS, defaulting to Linux
Warning: Cannot determine OS version, defaulting to 0.0
Warning: Cannot determine system type, defaulting to x86_64
sh: relocation error: /tmp/_MEIkoNPtY/lib/libc.so.6: symbol _dl_tls_get_addr_soft, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference
sh: relocation error: /tmp/_MEIkoNPtY/lib/libc.so.6: symbol _dl_tls_get_addr_soft, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference
IOError: [Errno 2] No such file or directory: '/tmp/_MEIkoNPtY/phylosift/phylosiftrc.orig'
```
We are currently using the following GLIBC version:

```
$ ldd --version
ldd (Debian EGLIBC 2.11.3-4+deb6u4) 2.11.3
Copyright (C) 2009 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

I just wanted to report this issue so that the authors are aware. As solving this may take some time, I am currently attempting to reinstall the pipeline via automated installation:

http://metamos.readthedocs.org/en/v1.5rc3/content/installation.html#automated-installation

I hope this method of installation goes well.

**Comment by skoren** [comment]
Hi,

Yes this is a known limitation of the frozen binary:
http://metamos.readthedocs.org/en/v1.5rc3/content/frozenbinary.html

This arises because the OS is compiled with a newer libgcc than is included in the frozen binary distribution. Since the frozen binary exists in it's own world, the libgcc is too old to allow shell tools (like sh, ls, etc) to run, causing crashes. We're looking into building using a newer libgcc while keeping backwards compatibility but in the meantime, the only way to run metAMOS on these systems is through the installation script.
