### ISSUE TITLE
Error at Annotate step

### ISSUE THREAD

**Issue by Ramanandan** [marbl/metAMOS#209]
Dear Dr. Sergey,

For sample (S002990), I executed following commands. Successfully, I got the outputs for annotation, functional annotation and classify.
#/bin/sh
../initPipeline -q -1 S002990_r1.fastq -2 S002990_r2.fastq -d S002990_Version1_1 -i 50:150
../runPipeline -q -v -a spades,velvet-sc,abyss,ray,edena,sga,masurca,soap,soap2,velvet -c FCP -g fraggenescan -p 15 -d S002990_Version1_1 -k 55 -f Preprocess,Assemble,MapReads,FindORFS,Annotate,FunctionalAnnotation,Propagate,FindRepeats,MultiAlign,Classify,Abundance,FindScaffoldORFS -n Scaffold

But for another sample (S00298A), 
1) initiPipeline - modified 2 input fastq files and output directory. Rest of them are same as the above command.
2) runpipeline - modified assembly to soap alone instead of spades,velvet-sc,abyss,ray,edena,sga,masurca,soap,soap2,velvet and output directory. Rest of them are same as the above command.

#/bin/sh
../initPipeline -q -1 S00298A_r1.fastq -2 S00298A_r2.fastq -d S00298A_Version1_2 -i 50:150
../runPipeline -q -v -a soap -c FCP -g fraggenescan -p 15 -d S00298A_Version1_2 -k 55 -f Preprocess,Assemble,MapReads,FindORFS,Annotate,FunctionalAnnotation,Propagate,FindRepeats,MultiAlign,Classify,Abundance,FindScaffoldORFS -n Scaffold

I encountered the errors at annotate step. What could have been the reason for this error.

![annotate error screenshot 1](https://cloud.githubusercontent.com/assets/11878969/7541411/39095dec-f583-11e4-8ee1-d8669700c16d.png)

![annotate error screenshot 2](https://cloud.githubusercontent.com/assets/11878969/7541348/b72cea96-f582-11e4-8b07-944081797204.png)

**Comment by nalandaatmi** [comment]
Dear Dr. Sergey,
Can you guide me to resolve the above issue. I have tried with different samples, still facing the same error for all of them. Interestingly for three other samples, I received the annotation and functional annotation outputs.

**Comment by Ramanandan** [comment]
Can I get some updates on this issue

**Comment by treangen** [comment]
Hi Ramanandan,

its possible that FCP crashed, you ran out of disk space, and/or the blast DB is missing (unlikely since previous run completed ), or other. Very hard to say without additional information, can you run the last command that failed , NB-BL.py  and send the output? Also,  I strongly recommend trying again with Kraken (-c kraken) for metagenomic classification .

**Comment by Ramanandan** [comment]
Dear Dr.Treangen,

I compared the files in ../annotate/out/ between the two samples. For sample S002988, I received the output, but sample S002992 I got errors at annotate step. I have pasted it for your reference.
![comparing two samples annotate output folder](https://cloud.githubusercontent.com/assets/11878969/7657012/88b4db04-fafc-11e4-88f1-5094351cf989.png)

**Comment by treangen** [comment]
You only need to rerun the command that failed. you have the full NB-BL.py command provided in the log file/screenshot you previously sent, so you can just copy and paste that command to run. If the command fails again, I'd strongly suggest that you contact the developers of FCP for support (since it worked previously for you, but not on your sample sample S002992) and/or try a different metagenomic classification tool, such as Kraken.

**Comment by skoren** [comment]
Closed, inactivity
