### ISSUE TITLE
Query Annotation based on mini kraken and custom kraken Database 

### ISSUE THREAD

**Issue by nalandaatmi** [marbl/metAMOS#220]
Dear Sergey/Treangen,

Query regarding Annotation:
My metagenomics forward and reverse fastq files have 20 million reads. After removing plant similar reads from my input fastq files using (fastq_screen pipeline), I had 4 million reads. Then I provided this fastq file (4 million reads) as input to metAMOS pipeline. FCP option has annotated those reads but each of the custom kraken database and minikraken did not annotate as expected. Can you comment on this issue?

I tried four different databases with metAMOS pipeline. 
1) Using minikraken database (DB size 4.5GB), for these 4 million reads I received an output with no hits in annotation.
![minikraken](https://cloud.githubusercontent.com/assets/12090134/8261795/50c70a0e-169b-11e5-8406-da405652366f.png)

2) Using custom kraken database (Bacterial, Viral, Archaeal, Fungal) (DB size 105GB), for the same input fastq file as above.
![custom krakendb bacteria archaea viral and fungal](https://cloud.githubusercontent.com/assets/12090134/8261890/0a312b3c-169c-11e5-9e7d-d60d0d5a84dc.png)

3) Using custom kraken database (nt database from ncbi) (DB size - 604GB), for the same input fastq file as above.
![custom kraken nt database](https://cloud.githubusercontent.com/assets/12090134/8261941/8c6aed22-169c-11e5-8cc9-7403c76d278f.png)

4) Using FCP database, for the same input fastq file as above.
![annotation based on fcp database](https://cloud.githubusercontent.com/assets/12090134/8261848/b9c7f586-169b-11e5-82e2-e280965da0f4.png)

**Comment by nalandaatmi** [comment]
Dear Sergey/Treangen, 

Have you got a chance to look in to this issue?

**Comment by skoren** [comment]
If you're not already, I'd suggest using the -u (annotate unassembled reads) option for runPipeline. This will significantly slow down FCP but Kraken should be OK. By default, only contigs are annotated but in your case more than 50% of the reads cannot be mapped to the assembled contigs (1.8M raw reads in the plots vs 3.5M input). 

Kraken has a post-filtering step which only keeps sequences it could assign with sufficient confidence. These could be filtering your hits. You can turn off this filtering by editing the Utilities/config/kraken.spec and setting the 0.05 filter to 0.00. However, this will increase the false-positive rate of the classifications. FCP does not have a similar filter, I believe which is why it provides more classifications. If you have more specific questions about the classifiers, I'd suggest contacting the developers for more info.

**Comment by kchambers58178** [comment]
I had similar results as above. I tried using the -u option and my results did not change. I am using metamos on a local supercomputer and am unable to change any files dealing with metamos. Is there any other suggestions for this problem?

**Comment by skoren** [comment]
Unfortunately, no you have to edit the Utilities/config/kraken.spec file to change the confidence setting for Kraken or use a custom database.

If you have other Kraken-specific questions, I'd suggest checking the Kraken support group.
