### ISSUE TITLE
unable to connect to host during metAmos installation

### ISSUE THREAD

**Issue by assafwww** [marbl/metAMOS#235]
Dear MetAmos developers,

I'm trying to install MetAmos but getting multiple "curl: (7) couldn't connect to host" errors, as seen below. I'm not sure if the problem stems from blocked connections by the server or that the target addresses do not exist, and would first ask how to test which of the two options is true.
If its an internet connectivity problem, is there a way to put all relevant component in the path so the installation program can recognize that and not complain, and if so which exact versions are needed ?
(and please see the error messages below)

thanks Assaf 

 python INSTALL.py core
<<Welcome to metAMOS install>>
Selected to install workflowName: CORE.
Will automatically install:
        Pysam
        Setuptools
        Fastqc
        Matplotlib
        Metavelvet
        Lap
        Kronatools
        Cython
        Sra
        Velvet
        Velvet-Sc
        Kraken
        Psutil
        Uniprot
        Amos
        Numpy

curl: (7) couldn't connect to host
tar: amos-binaries.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now

curl: (7) couldn't connect to host
tar: KronaTools-2.4.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
mv: cannot stat `KronaTools-2.4': No such file or directory
sh: line 0: cd: KronaTools: No such file or directory

....
sh: line 0: cd: KronaTools: No such file or directory
cat: KronaTools/taxonomy/taxonomy.tab: No such file or directory

**Comment by skoren** [comment]
I've checked the download links work on our system so it looks like a connectivity issue on your system. You can try running:

```
curl -L 'ftp://ftp.cbcb.umd.edu/pub/data/metamos/KronaTools-2.4.tar
```

to confirm. Unfortunately, there is no way to tell INSTALL.py to use local packages, it has to be able to download files from the internet because it runs other programs installation scripts which themselves download databases and other data. The best option is to fix the internet connectivity, if you can't do that, you could try the frozen binary instead.

**Comment by skoren** [comment]
Closed, inactivity.
