### ISSUE TITLE
Adding diamond as classification tool - Annotate

### ISSUE THREAD

**Issue by sejmodha** [marbl/metAMOS#237]
Hi There,
I am trying to add a new classification tool in the pipeline. I have managed to make the classification work and it produces a file called proba.hits but I can't create a Krona for the output.

As mentioned in the white paper, I need an ImportDiamond.pl in Utilities/perl/ directory. I have got that script in the Utilities directory but this script does not need a -f option as mentioned in the genericImport command in annotate.py as specified here. 

   elif generic.checkIfExists(STEP_NAMES.ANNOTATE, _cls.lower()):
      genericImport = "%s%sperl%sImport%s.pl"%(_settings.METAMOS_UTILS, os.sep, os.sep, _cls.title())
      if os.path.exists(genericImport):
         run_process(_settings, "perl %s %s -c -i -f %s %s/Annotate/out/%s.hits:%s/Assemble/out/%s.contig.cnt:%s"%(genericImport, "-l" if _settings.local_krona else "", listOfFiles, _settings.rundir,_settings.PREFIX,_settings.rundir, _settings.PREFIX, _settings.taxa_level),"Annotate")

I would like to run ImportDiamond.pl with just proba.hits without the %s.contig.cnt:%s bit, I have tried to modified the command but the pipeline fails without any apparent error message, expect it says that pipeline finished with errors.

What would be the best way to incorporate following command in the annotate.py or any other file from where it would be executed.

ImportDiamond proba.hits

Thanks for your help in advance.
Sej

**Comment by skoren** [comment]
You need to modify your script to support the command as metAMOS runs it if you're annotating contigs. The cnt file gives the number of reads per contig so that the classifications can be translated to read-counts rather than contig-counts. If your diamond classification runs on reads directly, you can still take the cnt parameter but just ignore it in your script.

To see more error details, runPipeline -v and look at the ANNOTATE.log file.

**Comment by skoren** [comment]
Closed, inactivity
